# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OGNjMzVjZmNlNTUwYjc3Y2Q5ODBjNTNlOTUxMzAyMDdkMGRhZGU0YTk2ZmUxODNmY2YwMGEzNTM5MzM4ZTU2NThjNTgxYjhjNDgwMTU3MmZhNGE0NDNmMWYxNjUzNTIzN2I3ZDA4MjJkMWFjZDZiYjhmYTBlNjE1NzRjMzFjMGM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
